name: GVR Pharma CI-CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Verify Application Files
        run: |
          echo "Checking project files"
          ls

      - name: Simulated Build
        run: |
          echo "Building application..."

      - name: Simulated Test
        run: |
          echo "Running tests..."

      - name: Simulated Deployment
        run: |
          echo "Deploying application..."
